version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: passkey_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
